//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kguthrie/Projects/RookAndPawn/kami-solver/kami-solver-core/src/main/java/com/rookandpawn/kami/solver/FastGraph.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_FastGraph")
#ifdef RESTRICT_FastGraph
#define INCLUDE_ALL_FastGraph 0
#else
#define INCLUDE_ALL_FastGraph 1
#endif
#undef RESTRICT_FastGraph

#if !defined (ComRookandpawnKamiSolverFastGraph_) && (INCLUDE_ALL_FastGraph || defined(INCLUDE_ComRookandpawnKamiSolverFastGraph))
#define ComRookandpawnKamiSolverFastGraph_

@class ComRookandpawnKamiSolverGraph;
@class IOSByteArray;

@interface ComRookandpawnKamiSolverFastGraph : NSObject

#pragma mark Public

- (instancetype)initWithComRookandpawnKamiSolverGraph:(ComRookandpawnKamiSolverGraph *)g;

- (jint)evaluateWithShort:(jshort)node
            withByteArray:(IOSByteArray *)colorSeq
                 withByte:(jbyte)finalColor;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (void)dealloc;

@end

J2OBJC_EMPTY_STATIC_INIT(ComRookandpawnKamiSolverFastGraph)

FOUNDATION_EXPORT void ComRookandpawnKamiSolverFastGraph_initWithComRookandpawnKamiSolverGraph_(ComRookandpawnKamiSolverFastGraph *self, ComRookandpawnKamiSolverGraph *g);

FOUNDATION_EXPORT ComRookandpawnKamiSolverFastGraph *new_ComRookandpawnKamiSolverFastGraph_initWithComRookandpawnKamiSolverGraph_(ComRookandpawnKamiSolverGraph *g) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComRookandpawnKamiSolverFastGraph *create_ComRookandpawnKamiSolverFastGraph_initWithComRookandpawnKamiSolverGraph_(ComRookandpawnKamiSolverGraph *g);

J2OBJC_TYPE_LITERAL_HEADER(ComRookandpawnKamiSolverFastGraph)

#endif

#pragma pop_macro("INCLUDE_ALL_FastGraph")
